/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/posts": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.posts.id"];
          title?: parameters["rowFilter.posts.title"];
          created_at?: parameters["rowFilter.posts.created_at"];
          updated_at?: parameters["rowFilter.posts.updated_at"];
          content?: parameters["rowFilter.posts.content"];
          status?: parameters["rowFilter.posts.status"];
          author_id?: parameters["rowFilter.posts.author_id"];
          tags?: parameters["rowFilter.posts.tags"];
          slug?: parameters["rowFilter.posts.slug"];
          description?: parameters["rowFilter.posts.description"];
          preview_image?: parameters["rowFilter.posts.preview_image"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["posts"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** posts */
          posts?: definitions["posts"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.posts.id"];
          title?: parameters["rowFilter.posts.title"];
          created_at?: parameters["rowFilter.posts.created_at"];
          updated_at?: parameters["rowFilter.posts.updated_at"];
          content?: parameters["rowFilter.posts.content"];
          status?: parameters["rowFilter.posts.status"];
          author_id?: parameters["rowFilter.posts.author_id"];
          tags?: parameters["rowFilter.posts.tags"];
          slug?: parameters["rowFilter.posts.slug"];
          description?: parameters["rowFilter.posts.description"];
          preview_image?: parameters["rowFilter.posts.preview_image"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.posts.id"];
          title?: parameters["rowFilter.posts.title"];
          created_at?: parameters["rowFilter.posts.created_at"];
          updated_at?: parameters["rowFilter.posts.updated_at"];
          content?: parameters["rowFilter.posts.content"];
          status?: parameters["rowFilter.posts.status"];
          author_id?: parameters["rowFilter.posts.author_id"];
          tags?: parameters["rowFilter.posts.tags"];
          slug?: parameters["rowFilter.posts.slug"];
          description?: parameters["rowFilter.posts.description"];
          preview_image?: parameters["rowFilter.posts.preview_image"];
        };
        body: {
          /** posts */
          posts?: definitions["posts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  posts: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    title: string;
    created_at?: string;
    updated_at?: string;
    content: string;
    status: "draft" | "published" | "removed";
    author_id: string;
    tags?: unknown[];
    slug: string;
    description: string;
    preview_image?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** posts */
  "body.posts": definitions["posts"];
  "rowFilter.posts.id": string;
  "rowFilter.posts.title": string;
  "rowFilter.posts.created_at": string;
  "rowFilter.posts.updated_at": string;
  "rowFilter.posts.content": string;
  "rowFilter.posts.status": string;
  "rowFilter.posts.author_id": string;
  "rowFilter.posts.tags": string;
  "rowFilter.posts.slug": string;
  "rowFilter.posts.description": string;
  "rowFilter.posts.preview_image": string;
}

export interface operations {}

export interface external {}
